services:
  backend:
    image: deepakrajasekaran/safetystudioweb:backend
    pull_policy: always
    container_name: safetystudio-backend
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--timeout", "120", "app:app"]
    expose:
      - "5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  frontend:
    image: deepakrajasekaran/safetystudioweb:frontend
    pull_policy: always
    container_name: safetystudio-frontend
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
