-- safety_export.db Schema Template
-- NOTE: Geometries generated by SafetyStudioWeb tool assume +Y is Forward and +X is Right.
-- The SafetyManagerNode expects ROS standard (+X is Forward, +Y is Left).
-- The C++ Node will automatically rotate these geometries by 90 degrees CCW during parsing.

CREATE TABLE IF NOT EXISTS geometries (
    name TEXT PRIMARY KEY,
    type TEXT NOT NULL, -- 'footprint', 'load', 'misc'
    wkt TEXT NOT NULL   -- e.g. POLYGON((...))
);

CREATE TABLE IF NOT EXISTS sensors (
    name TEXT PRIMARY KEY,
    x REAL NOT NULL,
    y REAL NOT NULL,
    mount_deg REAL NOT NULL,
    fov_deg REAL NOT NULL,
    range_m REAL NOT NULL,
    dia_m REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS physics_params (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evaluation_matrix (
    case_id INTEGER PRIMARY KEY,
    load_name TEXT NOT NULL,
    v_max REAL NOT NULL,
    w_max REAL NOT NULL,
    hardware_field_id INTEGER NOT NULL
);

-- Insert sample physics parameters (matching context.md)
INSERT INTO physics_params (key, value) VALUES ('tr', '0.1');
INSERT INTO physics_params (key, value) VALUES ('ac', '1.0');
INSERT INTO physics_params (key, value) VALUES ('ds', '0.1');
INSERT INTO physics_params (key, value) VALUES ('pad', '0.05');
INSERT INTO physics_params (key, value) VALUES ('smooth', '0.05');
INSERT INTO physics_params (key, value) VALUES ('lat_scale', '1.0');
INSERT INTO physics_params (key, value) VALUES ('shadow', '1');
INSERT INTO physics_params (key, value) VALUES ('include_load', '1');
INSERT INTO physics_params (key, value) VALUES ('patch_notch', '1');
INSERT INTO physics_params (key, value) VALUES ('field_method', 'union');
INSERT INTO physics_params (key, value) VALUES ('hull_threshold', '0.5');
INSERT INTO physics_params (key, value) VALUES ('nav_margin', '0.05');

-- Insert sample geometries
-- footprint (tool coords: Y is forward, X is right)
INSERT INTO geometries (name, type, wkt) VALUES (
    'footprint', 'footprint', 
    'POLYGON((-0.2 0.3, 0.2 0.3, 0.2 -0.3, -0.2 -0.3, -0.2 0.3))'
);

-- Load1
INSERT INTO geometries (name, type, wkt) VALUES (
    'Load1', 'load', 
    'POLYGON((0.2 0.3, 0.4 0.3, 0.4 -0.3, 0.2 -0.3, 0.2 0.3))'
);

-- Load2
INSERT INTO geometries (name, type, wkt) VALUES (
    'Load2', 'load', 
    'POLYGON((-0.4 0.3, -0.2 0.3, -0.2 -0.3, -0.4 -0.3, -0.4 0.3))'
);

-- Misc polygon
INSERT INTO geometries (name, type, wkt) VALUES (
    'Misc_Override_1', 'misc', 
    'POLYGON((1.0 1.0, 2.0 1.0, 2.0 2.0, 1.0 2.0, 1.0 1.0))'
);

-- NoLoad is technically empty or just base_footprint, but we can define an empty polygon
INSERT INTO geometries (name, type, wkt) VALUES (
    'NoLoad', 'load', 
    'POLYGON EMPTY'
);

-- Insert sample sensor
-- LiDAR at front center (tool coords: x=0, y=0.3)
INSERT INTO sensors (name, x, y, mount_deg, fov_deg, range_m, dia_m) VALUES (
    'LiDAR_Front', 0.0, 0.3, 0.0, 270.0, 5.0, 0.1
);

-- Insert sample evaluation matrix
INSERT INTO evaluation_matrix (case_id, load_name, v_max, w_max, hardware_field_id) VALUES (1, 'NoLoad', 0.5, 0.0, 101);
INSERT INTO evaluation_matrix (case_id, load_name, v_max, w_max, hardware_field_id) VALUES (2, 'NoLoad', 1.0, 0.0, 102);
INSERT INTO evaluation_matrix (case_id, load_name, v_max, w_max, hardware_field_id) VALUES (3, 'Load1', 0.5, 0.0, 201);
INSERT INTO evaluation_matrix (case_id, load_name, v_max, w_max, hardware_field_id) VALUES (4, 'Load1', 1.0, 0.0, 202);
